### ISSUE TITLE
unable to run with recent zig version

### ISSUE THREAD

**Issue by Time7Portal** [andrewrk/zig-vulkan-triangle#11]
(base) PS E:\Zig\Projects\zig-vulkan-triangle-master> zig build run
E:\Zig\Projects\zig-vulkan-triangle-master\build.zig:6:19: error: no field or member function named 'standardReleaseOptions' in 'Build'
    const mode = b.standardReleaseOptions();
                 ~^~~~~~~~~~~~~~~~~~~~~~~
C:\Zig\Zig-Compiler\lib\std\Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    runBuild__anon_7299: C:\Zig\Zig-Compiler\lib\std\Build.zig:1833:37
    steps__anon_7069: C:\Zig\Zig-Compiler\lib\build_runner.zig:914:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

**Comment by 10aded** [comment]
Yeah I got the same issue too.

**Comment by andrewrk** [comment]
fixed in 1c57bd38940cdadef5503adfeba8cd7a772197cb
